# Generated by Django 6.0.2 on 2026-03-22 06:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0008_alter_ingredient_group_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MealPlan',
            fields=[
                ('plan_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
            options={
                'db_table': 'meal_plan',
                'unique_together': {('start_date', 'end_date')},
            },
        ),
        migrations.CreateModel(
            name='MealPlanDetail',
            fields=[
                ('plan_detail_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('meal_type', models.CharField(choices=[('breakfast', 'Sáng'), ('lunch', 'Trưa'), ('dinner', 'Tối')], max_length=20)),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_plan_details', to='home.dish')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='mealplan.mealplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_plan_details', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'meal_plan_detail',
                'indexes': [models.Index(fields=['user', 'date'], name='meal_plan_d_user_id_a239e4_idx'), models.Index(fields=['plan', 'date'], name='meal_plan_d_plan_id_0d5438_idx')],
                'unique_together': {('plan', 'user', 'date', 'meal_type', 'dish')},
            },
        ),
    ]
