# Generated by Django 6.0.2 on 2026-03-24 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mealplan', '0002_shoppinglist_shoppingitem_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='shoppingitem',
            name='shopping_it_shoppin_1c62ed_idx',
        ),
        migrations.RemoveIndex(
            model_name='shoppingitem',
            name='shopping_it_plan_id_906db6_idx',
        ),
        migrations.RemoveIndex(
            model_name='shoppinglist',
            name='shopping_li_user_id_b6821d_idx',
        ),
        migrations.RemoveIndex(
            model_name='shoppinglist',
            name='shopping_li_user_id_93eb7f_idx',
        ),
        migrations.RemoveIndex(
            model_name='shoppinglist',
            name='shopping_li_plan_id_5e753e_idx',
        ),
        migrations.RemoveField(
            model_name='shoppinglist',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='shoppinglist',
            name='user',
        ),
        migrations.DeleteModel(
            name='ShoppingItem',
        ),
        migrations.DeleteModel(
            name='ShoppingList',
        ),
    ]
