# Generated by Django 6.0.2 on 2026-03-24 14:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0009_ingredient_is_system'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodInventory',
            fields=[
                ('food_inventory_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=0)),
                ('unit', models.CharField(blank=True, default='', max_length=20)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_inventories', to='home.ingredient')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_inventories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'food_inventory',
                'indexes': [models.Index(fields=['user', 'ingredient'], name='food_invent_user_id_d14e86_idx'), models.Index(fields=['user', 'ingredient', 'unit'], name='food_invent_user_id_ba6504_idx')],
                'unique_together': {('user', 'ingredient', 'unit')},
            },
        ),
    ]
