# Generated by Django 6.0.2 on 2026-03-11 13:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('dish_id', models.AutoField(primary_key=True, serialize=False)),
                ('dish_name', models.CharField(max_length=50, unique=True)),
                ('cooking_time', models.IntegerField()),
                ('ration', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='dishes/')),
                ('category_name', models.CharField(choices=[('Main Dish', 'Món chính'), ('Side Dish', 'Món phụ'), ('Salad', 'Salad'), ('Soup', 'Canh/Súp'), ('Dessert', 'Tráng miệng'), ('Drink', 'Đồ uống')], default='Main Dish', max_length=50)),
            ],
            options={
                'db_table': 'dish',
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('ingredient_id', models.AutoField(primary_key=True, serialize=False)),
                ('ingredient_name', models.CharField(max_length=50)),
                ('group_name', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'ingredient',
            },
        ),
        migrations.CreateModel(
            name='DishMethod',
            fields=[
                ('dish_method_id', models.AutoField(primary_key=True, serialize=False)),
                ('step_number', models.IntegerField()),
                ('instruction', models.TextField()),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='methods', to='home.dish')),
            ],
            options={
                'db_table': 'dish_method',
                'ordering': ['step_number'],
            },
        ),
        migrations.CreateModel(
            name='DishDetail',
            fields=[
                ('dish_detail_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('unit', models.CharField(max_length=10)),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dish_details', to='home.dish')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dish_details', to='home.ingredient')),
            ],
            options={
                'db_table': 'dish_detail',
            },
        ),
        migrations.CreateModel(
            name='IndividualDish',
            fields=[
                ('individual_id', models.AutoField(primary_key=True, serialize=False)),
                ('is_favorite', models.BooleanField(default=False, help_text='True: món yêu thích, False: món user tự tạo/thêm để quản lý')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='individual_dishes', to='home.dish')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='individual_dishes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'individual_dish',
                'unique_together': {('user', 'dish')},
            },
        ),
    ]
