# Generated by Django 6.0.2 on 2026-03-15 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='calories',
            field=models.IntegerField(blank=True, help_text='Lượng calo của món ăn (kcal)', null=True),
        ),
    ]
