# Generated by Django 6.0.2 on 2026-03-16 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_dish_calories'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='is_system',
            field=models.BooleanField(default=False, help_text='Đánh dấu đây là món mặc định của hệ thống'),
        ),
    ]
