# Generated by Django 6.0.2 on 2026-03-16 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_dish_is_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='source_dish',
            field=models.ForeignKey(blank=True, help_text='Món gốc của hệ thống nếu đây là món copy cho user', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cloned_dishes', to='home.dish'),
        ),
    ]
