# Generated by Django 6.0.2 on 2026-03-16 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_dish_source_dish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='dish_name',
            field=models.CharField(max_length=50),
        ),
    ]
