# Generated by Django 6.0.2 on 2026-03-17 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_dish_dish_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='category',
            field=models.CharField(choices=[('thực phẩm', 'Thực phẩm'), ('gia vị', 'Gia vị')], default='thực phẩm', max_length=50),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='group_name',
            field=models.CharField(choices=[('tất cả', 'Tất cả'), ('rau củ', 'Rau củ'), ('thịt', 'Thịt'), ('cá-hải sản', 'Cá - Hải sản'), ('sữa-trứng', 'Sữa - Trứng'), ('trái cây', 'Trái cây'), ('gia vị', 'Gia vị'), ('khác', 'Khác')], default='tất cả', max_length=50),
        ),
    ]
