# Generated by Django 6.0.2 on 2026-03-18 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_ingredient_group_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='group_name',
            field=models.CharField(choices=[('rau củ', 'Rau củ'), ('thịt', 'Thịt'), ('cá-hải sản', 'Cá - Hải sản'), ('sữa-trứng', 'Sữa - Trứng'), ('trái cây', 'Trái cây'), ('gia vị', 'Gia vị'), ('khác', 'Khác')], default='khác', max_length=50),
        ),
    ]
