# Generated by Django 6.0.2 on 2026-03-23 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_ingredient_group_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='is_system',
            field=models.BooleanField(default=False),
        ),
    ]
