# Generated by Django 6.0.2 on 2026-03-26 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppinglist', '0002_alter_shoppingitem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppinglist',
            name='source_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
